/**
 * Shared TypeScript schemas for BFIS ⇄ Olympus data contract.
 * 
 * These types define the interface between BFIS and DCSOlympus. They are imported
 * by both bfis-service and potentially frontend code to ensure type safety and
 * prevent schema drift.
 * 
 * Per spec: This file contains all shared TypeScript interfaces:
 * - OlympusUnitPosition, OlympusCoalition, OlympusUnit
 * - OlympusEvent, OlympusSnapshot
 * - BfisActionType, BfisActionTarget, BfisActionParams, BfisAction
 * - BfisDecision, CommandStatus, CommandResult
 * 
 * TODO: Implement all interfaces from the BFIS ⇄ Olympus Simple Strategy spec.
 */

/**
 * Type-safe coalition identifier for units.
 * 
 * Represents the coalition a unit belongs to in the battlefield.
 * Used in OlympusSnapshot and OlympusUnit to identify unit allegiance.
 * 
 * @see OlympusUnit
 * @see OlympusSnapshot
 */
export type OlympusCoalition = "BLUE" | "RED" | "NEUTRAL" | "UNKNOWN";

/**
 * 3D position for a unit on the battlefield.
 * 
 * Represents geographic coordinates and altitude for unit positioning.
 * All coordinates are in standard units (degrees for lat/lon, meters for altitude).
 * 
 * @see OlympusUnit
 */
export interface OlympusUnitPosition {
  /** Latitude in decimal degrees (-90 to 90) */
  lat: number;
  /** Longitude in decimal degrees (-180 to 180) */
  lon: number;
  /** Altitude in meters above sea level (non-negative) */
  altMeters: number;
}

/**
 * Represents a single unit on the battlefield.
 * 
 * Decoded from binary `/olympus/units` endpoint. Contains all essential
 * information about a unit's identity, position, and status.
 * 
 * @see OlympusSnapshot
 */
export interface OlympusUnit {
  /** Unique unit identifier (converted from uint32 in binary) */
  unitId: string;
  /** Group identifier if unit belongs to a group (converted from uint32, optional) */
  groupId?: string;
  /** Unit display name (optional) */
  name?: string;
  /** Unit coalition (BLUE, RED, NEUTRAL, UNKNOWN) */
  coalition: OlympusCoalition;
  /** High-level category (e.g., "Aircraft", "Helicopter", "GroundUnit", "NavyUnit") */
  category: string;
  /** Specific unit type (e.g., "F-16C_50", "AH-64D") */
  unitType: string;
  /** Unit position (lat, lon, altitude) */
  position: OlympusUnitPosition;
  /** Unit status/state (e.g., "idle", "attack", "follow", optional) */
  status?: string;
}

/**
 * Represents a battlefield event derived from logs or snapshot diffing.
 * 
 * Events capture significant state changes in the battlefield (e.g., unit destroyed,
 * unit spawned, mission start). Events are optional in MVP and may be derived
 * from log analysis or snapshot comparison.
 * 
 * @see OlympusSnapshot
 */
export interface OlympusEvent {
  /** Unique event identifier (generated by BFIS) */
  eventId: string;
  /** ISO 8601 timestamp of event */
  time: string;
  /** Event type (e.g., "unit_destroyed", "unit_spawned", "mission_start") */
  type: string;
  /** Associated unit ID if applicable (optional) */
  unitId?: string;
  /** Additional event-specific data (optional) */
  details?: Record<string, unknown>;
}

/**
 * Represents a point-in-time view of the battlefield state as reported by Olympus.
 * 
 * This is the primary output of `SnapshotReader.readOnce()`. Contains mission
 * metadata, all units on the battlefield, and optional events. Snapshots are
 * immutable once created (FR-018).
 * 
 * @see SnapshotReader.readOnce
 */
export interface OlympusSnapshot {
  /** UUID v4 identifier for this snapshot (generated by BFIS) */
  snapshotId: string;
  /** Mission identifier from Olympus `/olympus/mission` response */
  missionId: string;
  /** Server identifier from Olympus `/olympus/mission` response */
  serverId: string;
  /** Olympus session hash used to detect mission resets */
  sessionHash: string;
  /** ISO 8601 timestamp of snapshot creation (from latest endpoint response) */
  time: string;
  /** Array of decoded units (always present, may be empty) */
  units: OlympusUnit[];
  /** Optional derived events from logs or snapshot diffing (MVP: optional) */
  events?: OlympusEvent[];
}
