import type { BfisContextSnapshot } from "../context/types.js";
import type {
  BfisDecision,
  OlympusCoalition,
} from "../../../shared-schemas/index.js";

/**
 * Tactical summary generated by the Intel agent from a battlefield snapshot.
 *
 * This structure is intentionally coarse-grained and stable so that:
 * - LLM prompts stay compact and easier to control.
 * - Downstream decision logic (Commander) can evolve without touching
 *   decoder-level schemas or Olympus internals.
 */
export interface TacticalSummary {
  /**
   * Unit counts by coalition (for example BLUE, RED, NEUTRAL, UNKNOWN).
   * Keys must match {@link OlympusCoalition} values.
   */
  unitCounts: Record<OlympusCoalition, number>;

  /**
   * Unit counts by category (for example "Aircraft", "GroundUnit").
   * Categories are derived from normalized context, not binary decoder enums.
   */
  categoryCounts: Record<string, number>;

  /**
   * Key positions on the battlefield, such as airbases, bullseyes,
   * or detected unit clusters.
   *
   * These positions allow the Commander to reason about geography
   * without needing the full raw snapshot in every prompt.
   */
  keyPositions: Array<{
    type: "airbase" | "bullseye" | "cluster";
    /**
     * Coalition that controls this position, when applicable.
     * For example, an airbase may be BLUE controlled.
     */
    coalition?: OlympusCoalition;
    /**
     * Geodetic position of the key point.
     * Altitude is optional because not all positions are 3D (for example bullseye).
     */
    position: {
      lat: number;
      lon: number;
      altMeters?: number;
    };
    /**
     * Human-readable label (for example airbase name, cluster id).
     */
    label?: string;
  }>;

  /**
   * High-level threat assessment derived from unit positions and types.
   * This is deliberately simplified for MVP and can be refined later.
   */
  threats: Array<{
    /** Coalition that poses the threat. */
    coalition: OlympusCoalition;
    /** Short description suitable for LLM consumption and logging. */
    description: string;
    /** Coarse severity band used for prioritization. */
    severity: "low" | "medium" | "high";
  }>;

  /**
   * Timestamp of the snapshot this summary is based on (ISO 8601).
   * Mirrors {@link BfisContextSnapshot.base.time}.
   */
  snapshotTime: string;

  /**
   * Snapshot ID for traceability and correlation with logs.
   * Mirrors {@link BfisContextSnapshot.base.snapshotId}.
   */
  snapshotId: string;
}

/**
 * Delta between two snapshots, detecting changes in battlefield state.
 *
 * Intel uses this to highlight what materially changed so the Commander
 * does not need to re-parse the full snapshot history.
 */
export interface SnapshotDelta {
  /** New units that appeared since the previous snapshot. */
  newUnits: Array<{
    unitId: string;
    coalition: OlympusCoalition;
    /** High-level category such as "Aircraft" or "GroundUnit". */
    category: string;
  }>;

  /** Units that disappeared (destroyed or despawned). */
  destroyedUnits: Array<{
    unitId: string;
    coalition: OlympusCoalition;
  }>;

  /** Units whose positions changed significantly (beyond configured threshold). */
  movedUnits: Array<{
    unitId: string;
    oldPosition: {
      lat: number;
      lon: number;
    };
    newPosition: {
      lat: number;
      lon: number;
    };
  }>;

  /**
   * True when overall hostility status changed between snapshots.
   * The underlying source of truth is Olympus hostility logic;
   * Intel only reports the change, it does not compute hostilities itself.
   */
  hostilityChanged: boolean;

  /** Timestamp of previous snapshot (ISO 8601). */
  previousSnapshotTime: string;

  /** Timestamp of current snapshot (ISO 8601). */
  currentSnapshotTime: string;
}

/**
 * Mission context wrapper providing metadata for decision-making.
 *
 * This bridges the normalized snapshot world into Commander prompts
 * without exposing low-level Olympus implementation details.
 */
export interface MissionContext {
  /** Unique mission identifier from Olympus context. */
  missionId: string;
  /** Server identifier hosting this mission. */
  serverId: string;
  /** Session hash that changes on mission reset or restart. */
  sessionHash: string;
  /** Current mission time (ISO 8601), typically from the snapshot base. */
  time: string;
  /**
   * Whether hostilities have started, as defined by Olympus.
   * BFIS does not infer or override this flag.
   */
  hostilitiesStarted: boolean;
}

/**
 * Output from Intel agent, containing tactical summary and detected changes.
 *
 * This is the primary input to the Commander agent and is also useful
 * for logging and NDJSON decision records.
 */
export interface IntelAgentOutput {
  /** Tactical summary describing the current battlefield state. */
  summary: TacticalSummary;
  /** Optional detected changes versus previous snapshot. */
  changes?: SnapshotDelta;
  /** Timestamp when Intel produced this output (ISO 8601). */
  timestamp: string;
  /**
   * Raw snapshot for reference (optional).
   * This may be omitted to save tokens when constructing LLM prompts,
   * but keeping it here simplifies traceability for logs and tests.
   */
  rawSnapshot?: BfisContextSnapshot;
}

/**
 * Input to Commander agent, containing Intel output and previous decision context.
 *
 * This isolates decision-making concerns from raw decoder formats and
 * provides a stable contract for both LLM-driven and rules-based logic.
 */
export interface CommanderAgentInput {
  /** Tactical summary prepared by the Intel agent. */
  intelSummary: TacticalSummary;
  /** Optional snapshot delta to highlight what changed. */
  changes?: SnapshotDelta;
  /** Mission metadata and hostility status derived from context. */
  missionContext: MissionContext;
  /** Previous decision used for continuity between decision cycles. */
  previousDecision?: BfisDecision;
  /**
   * Player intent, when running in Copilot / assistant mode.
   * This is typically captured from external UI or intent modules.
   */
  playerIntent?: string;
}

/**
 * Input to Writer agent, containing Commander's decision and command mapping context.
 *
 * Writer is responsible for translating these decisions into concrete
 * Olympus API calls via the Command Adapter layer.
 */
export interface WriterAgentInput {
  /** Decision produced by Commander (LLM or rules-based). */
  decision: BfisDecision;
  /**
   * Names of available command mappings, typically derived from
   * bfis_action_command_mapping documentation or configuration.
   */
  availableCommands: string[];
}

/**
 * Result of attempting to execute a single mapped command.
 *
 * This mirrors what the orchestrator records in AgentState so that
 * command lifecycles can be inspected and replayed later if needed.
 */
export interface CommandResult {
  /** Hash or identifier used to correlate with Olympus command tracking. */
  commandHash: string;
  /** Lifecycle status of this command from BFIS' perspective. */
  status: "PENDING" | "SENT" | "CONFIRMED" | "FAILED" | "LOGGED";
  /** Optional error message when status is FAILED. */
  error?: string;
}

/**
 * Structured representation of an error raised by one of the agents
 * or the orchestrator itself.
 *
 * This is propagated via AgentState so that errors are observable,
 * loggable, and can participate in recovery decisions.
 */
export interface AgentError {
  /** Agent that reported the error (by logical role). */
  agent: "intel" | "commander" | "writer" | "orchestrator";
  /** Human-readable error message for logs and debugging. */
  message: string;
  /** Timestamp when the error occurred (ISO 8601). */
  timestamp: string;
  /**
   * True when downstream agents can continue (for example with degraded data),
   * false when the orchestrator should treat this as fatal for the cycle.
   */
  recoverable: boolean;
}

/**
 * LangGraph state schema for multi-agent orchestration.
 *
 * All agents read from and write to this shared state object.
 * The orchestrator treats this structure as immutable, returning
 * new state snapshots between nodes.
 */
export interface AgentState {
  /** Current battlefield snapshot (from SnapshotReader). */
  currentSnapshot: BfisContextSnapshot | null;

  /** Previous snapshot used for change detection in Intel. */
  previousSnapshot: BfisContextSnapshot | null;

  /** Intel agent output (tactical summary + changes). */
  intelOutput: IntelAgentOutput | null;

  /** Commander agent input (derived from intelOutput + mission context). */
  commanderInput: CommanderAgentInput | null;

  /** Commander agent decision for this cycle. */
  decision: BfisDecision | null;

  /** Writer agent input (derived from decision and mapping context). */
  writerInput: WriterAgentInput | null;

  /** Results of command execution (or dry-run mapping) for this cycle. */
  commandResults: CommandResult[] | null;

  /** Error state if any agent or the orchestrator encountered a problem. */
  error: AgentError | null;

  /**
   * Human approval flag for Copilot / human-in-the-loop mode.
   * When undefined or null, approval has not yet been recorded.
   */
  userApproval?: boolean | null;

  /** Unique identifier for this orchestrator cycle (for example UUID). */
  cycleId: string;

  /** Timestamp when the cycle started (ISO 8601). */
  cycleStartTime: string;

  /** Timestamp when the cycle completed, or null if in progress (ISO 8601). */
  cycleEndTime: string | null;
}

